{% set version = "0.1.0" %}

package:
  name: grig
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/g/grig/grig-{{ version }}.tar.gz
  sha256: 06aa9204932bcadb4060fee9a22798ba194d115fc94140f43aaf97f732f8bb46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps

requirements:
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm
  host:
    - pip
    - python>=3.8
  run:
    - bottleneck>=1.3.1
    - cloudpickle>=1.6.0
    - imageio>=2.9.0
    - joblib>=0.14.1
    - matplotlib>=3.3
    - numba>=0.53.1
    - numpy>=1.5.0
    - pip>=20.3
    - psutil>=5.8.0
    - pytest>=5.3.5
    - pytest-cov>=2.8.1
    - python>=3.9
    - scikit-learn>0.22.1
    - scipy>=1.4.1
    - sphinx>=5

test:
  imports:
    - grig

about:
  home: https://sofia-usra.github.io/grig/
  dev_url: https://github.com/SOFIA-USRA/grig
  license: BSD-3-Clause
  summary: 'N-Dimensional Resampler for Irregularly Gridded Data'
  description: |
    Grig is a fully N-dimensional resampling package for irregularly gridded data. It
    was primarily developed for generating astronomical image mosaics and spectral
    image cubes, but has broad applicability to scientific data arrays with or
    without associated errors.
